document.write(" <ul class=\"menu\" id=\"menu\"> ");
document.write("     <li> <a href=\"#\" class=\"menulink\"> Partecipanti </a> " );
document.write("          <ul> " );
document.write("               <li> <a href=\"playersname.html\"> Ordinati per nome </a> </li>" );
document.write("               <li> <a href=\"index.html\"> Ordinati per Elo </a> </li>" );
document.write("               <li> <a href=\"tourstat.html\"> Statistiche </a> </li>" );
document.write("          </ul> " );
document.write("     </li> " );
document.write("     <li> <a href=\"#\" class=\"menulink\"> Tabellone </a> " );
document.write("          <ul> " );
document.write("               <li> <a href=\"crosstable.html\"> ordinato per ID </a> </li>" );
document.write("               <li> <a href=\"crosstablescore.html\"> ordinato per punteggio </a> </li>" );
document.write("               <li> <a href=\"standing.html\"> Classifica </a> </li>" );
document.write("               <li> <a href=\"rankinggroup.html\"> Classifiche di gruppo </a> </li>" );
document.write("          </ul> " );
document.write("     </li> " );
document.write("     <li> <a href=\"#\" class=\"menulink\"> Turno </a> " );
document.write("          <ul> " );
document.write("               <li> <a href=\"#\" class=\"sub\"> Turno1 </a> " );
document.write("                    <ul> " );
document.write("                          <li class=\"topline\"> <a href=\"pairs1.html\" > Abbinamenti </a> </li>" );
document.write("                    </ul> " );
document.write("               </li> " );
document.write("               <li> <a href=\"#\" class=\"sub\"> Turno2 </a> " );
document.write("                    <ul> " );
document.write("                          <li class=\"topline\"> <a href=\"pairs2.html\" > Abbinamenti </a> </li>" );
document.write("                    </ul> " );
document.write("               </li> " );
document.write("               <li> <a href=\"#\" class=\"sub\"> Turno3 </a> " );
document.write("                    <ul> " );
document.write("                          <li class=\"topline\"> <a href=\"pairs3.html\" > Abbinamenti </a> </li>" );
document.write("                    </ul> " );
document.write("               </li> " );
document.write("               <li> <a href=\"#\" class=\"sub\"> Turno4 </a> " );
document.write("                    <ul> " );
document.write("                          <li class=\"topline\"> <a href=\"pairs4.html\" > Abbinamenti </a> </li>" );
document.write("                    </ul> " );
document.write("               </li> " );
document.write("               <li> <a href=\"#\" class=\"sub\"> Turno5 </a> " );
document.write("                    <ul> " );
document.write("                          <li class=\"topline\"> <a href=\"pairs5.html\" > Abbinamenti </a> </li>" );
document.write("                    </ul> " );
document.write("               </li> " );
document.write("               <li> <a href=\"#\" class=\"sub\"> Turno6 </a> " );
document.write("                    <ul> " );
document.write("                          <li class=\"topline\"> <a href=\"pairs6.html\" > Abbinamenti </a> </li>" );
document.write("                    </ul> " );
document.write("               </li> " );
document.write("               <li> <a href=\"#\" class=\"sub\"> Turno7 </a> " );
document.write("                    <ul> " );
document.write("                          <li class=\"topline\"> <a href=\"pairs7.html\" > Abbinamenti </a> </li>" );
document.write("                    </ul> " );
document.write("               </li> " );
document.write("               <li> <a href=\"#\" class=\"sub\"> Turno8 </a> " );
document.write("                    <ul> " );
document.write("                          <li class=\"topline\"> <a href=\"pairs8.html\" > Abbinamenti </a> </li>" );
document.write("                    </ul> " );
document.write("               </li> " );
document.write("          </ul> " );
document.write("     </li> " );
document.write("     <li> <a href=\"#\" class=\"menulink\"> Report </a> " );
document.write("          <ul> " );
document.write("               <li> <a href=\"playercard.html\"> Cartellino nazionale </a> </li>" );
document.write("          </ul> " );
document.write("     </li> " );
document.write("</ul> " );
