document.write(" <ul class=\"menu\" id=\"menu\"> ");
document.write("     <li> <a href=\"#\" class=\"menulink\"> Partecipanti </a> " );
document.write("          <ul> " );
document.write("               <li> <a href=\"playersname.html\"> Ordinati per nome </a> </li>" );
document.write("               <li> <a href=\"index.html\"> Ordinati per Elo </a> </li>" );
document.write("               <li> <a href=\"tourstat.html\"> Statistiche </a> </li>" );
document.write("          </ul> " );
document.write("     </li> " );
document.write("     <li> <a href=\"#\" class=\"menulink\"> Tabellone </a> " );
document.write("          <ul> " );
document.write("               <li> <a href=\"crosstable.html\"> Ordinato per ID </a> </li>" );
document.write("               <li> <a href=\"crosstablescore.html\"> Ordinato per punti </a> </li>" );
document.write("               <li> <a href=\"standing.html\"> Classifica </a> </li>" );
document.write("               <li> <a href=\"rankinggroup.html\"> Classifiche per gruppi Elo </a> </li>" );
document.write("               <li> <a href=\"rankingagegroup.html\"> Classifica per gruppi di età </a> </li>" );
document.write("          </ul> " );
document.write("     </li> " );
document.write("     <li> <a href=\"#\" class=\"menulink\"> Abbinamento </a> " );
document.write("          <ul> " );
document.write("         <li> <a href=\"pairs1.html\" > Turno 1 </a> </li>" );
document.write("         <li> <a href=\"pairs2.html\" > Turno 2 </a> </li>" );
document.write("         <li> <a href=\"pairs3.html\" > Turno 3 </a> </li>" );
document.write("         <li> <a href=\"pairs4.html\" > Turno 4 </a> </li>" );
document.write("         <li> <a href=\"pairs5.html\" > Turno 5 </a> </li>" );
document.write("         <li> <a href=\"pairs6.html\" > Turno 6 </a> </li>" );
document.write("         <li> <a href=\"pairs7.html\" > Turno 7 </a> </li>" );
document.write("         <li> <a href=\"pairs8.html\" > Turno 8 </a> </li>" );
document.write("          </ul> " );
document.write("     </li> " );
document.write("     <li> <a href=\"#\" class=\"menulink\"> Report </a> " );
document.write("          <ul> " );
document.write("               <li> <a href=\"nelovar.html\"> Elo Nazionale </a> </li>" );
document.write("               <li> <a href=\"playercard.html\"> Cartellino nazionale </a> </li>" );
document.write("          </ul> " );
document.write("     </li> " );
document.write("</ul> " );
